version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: go_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
